### ISSUE TITLE
Upgrade to Node.js 16 needed due to deprecation

### ISSUE THREAD

**Issue by dcastil** [apexskier/github-release-commenter#426]
Hi @apexskier! 👋 Thanks for this awesome GitHub Action! I use it for [tailwind-merge](https://github.com/dcastil/tailwind-merge) and love it.

I noticed a deprecation warning in [one of my GitHub action workflows](https://github.com/dcastil/tailwind-merge/actions/runs/4616854327):

> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: apexskier/github-release-commenter@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

Would be nice to resolve that. I don't know too much about GitHub Actions but seems like the version only needs to be updated here: https://github.com/apexskier/github-release-commenter/blob/v1.3.2/action.yml#L26

**Comment by apexskier** [comment]
Update has been released!
