### ISSUE TITLE
Bug: multiple comments posted on PRs

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [apexskier/github-release-commenter#433]
https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues/427 had one comment posted on it: 
* https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues/427#issuecomment-1546456600

...while its linked PR https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues/401#issuecomment-1546443533 only had one:
* https://github.com/JoshuaKGoldberg/template-typescript-node-package/pull/428#issuecomment-1546456601
* https://github.com/JoshuaKGoldberg/template-typescript-node-package/pull/428#issuecomment-1546456611

This looks like a bug?

Edit: Aha, @navin-moorthy is right - updated. I mixed them up. 😄

**Comment by navin-moorthy** [comment]
In my research, it seems in issues it posts single comments & in prs it posts two comments.

**Comment by JoshuaKGoldberg** [comment]
Ah, I was wrong - sorry for the noise & thanks for the catch @navin-moorthy!

https://github.com/JoshuaKGoldberg/template-typescript-node-package/pull/535
