### ISSUE TITLE
HttpError: Resource not accessible by integration

### ISSUE THREAD

**Issue by johnnyreilly** [apexskier/github-release-commenter#545]
I've encountered this issue when working with repos templated with Create TypeScript App. https://github.com/JoshuaKGoldberg/create-typescript-app/issues/1682

I'm not sure if it's an issue with CTA, but I couldn't spot anything obvious.

The workflow I have using the action fails with:

> Error: HttpError: Resource not accessible by integration
> Error: Resource not accessible by integration

https://github.com/johnnyreilly/azdo-npm-auth/actions/runs/12107959311/job/33755423218

cc @joshuakgoldberg

**Comment by JoshuaKGoldberg** [comment]
I've seen this error in the past when permissions are lacking. Most commonly either from missing an `ACCESS_TOKEN` env variable or from it not having the requisite permissions.

Reference: https://github.com/JoshuaKGoldberg/create-typescript-app/issues/1682

**Comment by johnnyreilly** [comment]
My tokens have _repo_ and _workflow_ permissions as per:

https://github.com/JoshuaKGoldberg/create-typescript-app/blob/e65eae3e00d797ce0d88b5a1eb9707c857c66944/docs/Initialization.md?plain=1#L24

I guess the question is, is that sufficient?

**Comment by johnnyreilly** [comment]
Thanks for testing!

Yup I am using `secrets.GITHUB_TOKEN`:

https://github.com/johnnyreilly/azdo-npm-auth/blob/ead5d8f3fd93f6b984b4cd444d6f6c20539a31ef/.github/workflows/post-release.yml#L11

So do you reckon we maybe avoid using the built in token and create our own?

**Comment by apexskier** [comment]
I'm still not sure if GitHub changed something or not, but I'd recommend manually specifying issue write permissions [in your workflow yaml file](https://github.com/apexskier/test-github-release-commenter/commit/50cc158a04edf2ca4a327b8242a3ffc76d1cfa06):

```yml
permissions:
  issues: write
```

I confirmed that does work in a test repository.

<details>

<summary>Debug notes</summary>

Starting with action file

```yaml
on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: apexskier/github-release-commenter@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment-template: |
            Release {release_link} addresses this.
```

With ![Actions settings · apexskiertest-github-release-commenter - Safari - 2024-12-02 at 19 03 11@2x](https://github.com/user-attachments/assets/f559485e-eff8-4814-a5f0-d555c233b1b8)

Reproduced bug at https://github.com/apexskier/test-github-release-commenter/actions/runs/12131310457/job/33823215798

---

![Actions settings · apexskiertest-github-release-commenter - Safari - 2024-12-02 at 19 05 00@2x](https://github.com/user-attachments/assets/9918b01e-9579-4e3d-9422-58b1c2378a99)

Run succeeded and commented https://github.com/apexskier/test-github-release-commenter/actions/runs/12131548635, https://github.com/apexskier/test-github-release-commenter/issues/3#issuecomment-2513379117

---

Back to ![Actions settings · apexskiertest-github-release-commenter - Safari - 2024-12-02 at 19 03 11@2x](https://github.com/user-attachments/assets/f559485e-eff8-4814-a5f0-d555c233b1b8), but with a manual permissions key https://github.com/apexskier/test-github-release-commenter/commit/50cc158a04edf2ca4a327b8242a3ffc76d1cfa06


</details>

**Comment by johnnyreilly** [comment]
I'll try that today thanks!

BTW here's two examples of the initial release working on the first attempt but failing on the second:

- https://github.com/investec/home-run/actions/workflows/post-release.yml
- https://github.com/investec/home-run/actions/workflows/post-release.yml

**Comment by apexskier** [comment]
> BTW here's two examples of the initial release working on the first attempt but failing on the second:

That's expected on first release - the action doesn't do anything on first release. (originally intended because you can have a long backlog of affected issues/PRs and can have some issues due to the volume)

![v0 2 0 · investechome-run@ce2bfe1 - Safari - 2024-12-05 at 10 42 10@2x](https://github.com/user-attachments/assets/4f4a2d34-34da-4494-b311-9419d0a6ba82)

**Comment by johnnyreilly** [comment]
It worked!  Take a look at https://github.com/johnnyreilly/azdo-npm-auth/actions/runs/12211680069/job/34069255562

<img width="974" alt="image" src="https://github.com/user-attachments/assets/19689bab-f44d-4b65-8615-50199f6a4e11">

And look at the history of this action: 

<img width="1642" alt="image" src="https://github.com/user-attachments/assets/d8c4f98c-9d50-48ef-a4a8-59a2a0d7772f">

So yeah, I think the

```yml
permissions:
  issues: write
  pull-requests: write
```

is key.   Thanks for the help!

**Comment by apexskier** [comment]
Thanks for confirming!
